### ISSUE TITLE
Not available for Python 3?

### ISSUE THREAD

**Issue by chaintip** [oskyk/cashaddress#1]
Hi oskyk

Thanks for this library!

However, I get:
pip install cashaddress
Collecting cashaddress
  Downloading cashaddress-1.0.0.tar.gz
cashaddress requires Python '>=2.7,<3' but the running Python is 3.6.1

Is it not available for Python 3?

**Comment by oskyk** [comment]
Hello it doesn't work with python3 for some weird reason, I will investigate and try to fix it in future

**Comment by chaintip** [comment]
I get the following addresses when I try and use it with python 3. They are different to what other services show me: 

13BarZawnv4tZji4kBZt9gWgFyKUHUmpMW
bitcoincash:qp38jar9v9e8ycte9p3zwhrcxym4c7rxxpw8sctzt3ux2wzu0qck2jzu0p3nzjnf23w8scfj03m4c7rrxvlryhrc89j4c7pex95nsfef8xk7mycc

13BarZKt5mZmdFBCj3ziXApVCeUJTkz8qD
bitcoincash:qp38jar9v9e8ycte9p3zwhrcxym4c7rxxpw8sctzt3ux2v6u0pjn2hrcxqe9c7rrx3w8se3484w8swtrt3uxzvzu0p3xz62u0quxg42u0quxxhrc8y6xc4ju0qunxfef2wvrmy4c

12MniXbU2Et5zpWzjvjjZR13BaqXBN88k5
bitcoincash:qp38jar9v9e8ycte9p3zwhrcxpj4c7r9xew8swtz2aw8sc3kt3uxgct7t3urqc6u0qunjv2u0pnr2w6u0pjkyj6u0qcrwhrcv5u4c7rxx9m45hrcvgezw2gc4dmht97

13BaqaunyuWTYLF39wjkNsw74V2n6UUS6E
bitcoincash:qp38jar9v9e8ycte9p3zwhrcxym4c7rxxpw8scfcfeeyuaju0pnrzkzu0pjxxhrc8yc9c7p38pw8sceet3ursd6u0qunjhrcx9j85hrcv3j9c7rx89w8scf5yu5sc949xd2c

**Comment by oskyk** [comment]
Yes they are because python3 string/bytes conversion I coded it for python2 originally and that's the reason why pip is restricted to python2 only, I will try to make it for python3 too in future but currently I do not have enough time for that

**Comment by oskyk** [comment]
It should be working now

**Comment by chaintip** [comment]
Thank you!
