### ISSUE TITLE
MIT license possible?

### ISSUE THREAD

**Issue by gandrewstone** [oskyk/cashaddress#4]
We'd like to use this in the bitcoin cash client interop testing framework.  But we would like to minimize dependencies so would like to use your files directly, with attribution of course.  Since you have used the GPL V3 license we can't incorporate it.  Are you willing to also license this code using the standard MIT license that Bitcoin Cash currently uses?

**Comment by ghost** [comment]
I would also appreciate this.

**Comment by oskyk** [comment]
License has been change feel free to use the code

**Comment by ghost** [comment]
Fantastic, thank you!

**Comment by l0rb** [comment]
Maybe a dual license MIT/GPL would be good, for those that want to publish a fork with GPL.
